spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_center?serverTimezone=Asia/Shanghai
    hikari:
      username: root
      password: jmr980328
      driver-class-name: com.mysql.cj.jdbc.Driver
      auto-commit: true
      #空闲连接超时时长
      idle-timeout: 60000
      #连接超时时长
      connection-timeout: 60000
      #最大生命周期，0不过期
      max-lifetime: 0
      #最小空闲连接数
      minimum-idle: 10
      #最大连接数量
      maximum-pool-size: 10

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  #        namespace: 0e5a522d-9b74-4833-af36-35297b3e50fb
  #        cluster-name: NJ
  application:
    name: project-center
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 0
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8083
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: user-group

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true #pageSize=0


feign:
  client:
    config:
      default:
        requestInterceptors:
          - com.jmr.projectcenter.feignclient.interceptor.TokenRelayRequestInteceptor
logging:
  level:
    com.jmr.projectcenter.feignclient.UserCenterFeignClient: debug
#    com.jmr.projectcenter.dao: debug

rocketmq:
  producerId: GID-ActivityProducer
  consumerId: GID-ActivityConsumer
  msgTopic: add-activity #生产主题
  accessKey: LTAI4Fsk3ufKP5w3LN61QHhp  #连接通道
  secretKey: zAGppLb9O9FWCaGCYi2Bl76sGGZw1T  #连接秘钥
  onsAddr: http://MQ_INST_1297517832308950_BcgfHYIU.cn-shanghai.mq-internal.aliyuncs.com:8080  #生产者ons接入域名
  #dev http://MQ_INST_1297517832308950_Bceo8QWE.mq-internet-access.mq-internet.aliyuncs.com:80
  #prod http://MQ_INST_1297517832308950_BcgfHYIU.cn-shanghai.mq-internal.aliyuncs.com:8080